
SCREEN_WIDTH = 400
SCREEN_HEIGHT = 400

MAIN_WIN_WIDTH = 400
MAIN_WIN_HEIGHT = 400

LOGIN_WIN_WIDTH = 400
LOGIN_WIN_HEIGHT = 400

REGISTER_WIN_WIDTH = 400
REGISTER_WIN_HEIGHT = 400

TITLE_BG_CLR = "#000000"


MAIN_WIN_TITLE = "Sign in SQL"
LOGIN_WIN_TITLE = "Login"
REGISTER_WIN_TITLE = "Register"

SUC_TITLE = "Success!"
