

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

MAIN_TITLE = "Login SQL"

BTN_FONT = ("Calibri", 50)
BTN_PAD_Y = 10
BTN_BG_CLR = "#CFCFCF"
BTN_CLR_ON_CLICK = '#ABABAB'

BTN_WIDTH = 10
BTN_HEIGHT = 1

TITLE_TXT_FONT = ("Calibri", 100)
TITLE_BG_CLR = "#8E8E8E"

SIGN_IN_TITLE_TXT = "Sign In"
SIGN_IN_TITLE_HEIGHT = 1

LOGIN_WINDOW_WIDTH = 400
LOGIN_WINDOW_HEIGHT = 300

LOGIN_TXT_INPUT_WIDTH = LOGIN_WINDOW_WIDTH
LOGIN_TXT_INPUT_HEIGHT = 1
LOGIN_TXT_FONT = ("Calibri", 20)

REGISTER_WINDOW_WIDTH = 400
REGISTER_WINDOW_HEIGHT = 400
